### ISSUE TITLE
npmjs.com package is old

### ISSUE THREAD

**Issue by JiffishHank** [Panman8201/ember-cli-bootswatch#11]
Please push a new update

**Comment by Panman8201** [comment]
Can you expand on this? What exactly is "old"? From what I can tell, no package.json changes have been made to ember-cli addon's since this was created.

**Comment by Panman8201** [comment]
@JiffishHank Are you perhaps making note of the old chalk dependency version? That update was made some time ago but I just released a new version that includes the update. Please let me know. Thanks
