### ISSUE TITLE
ember-cli-bootswatch not working with ember-cli v2.4.2?

### ISSUE THREAD

**Issue by ShenglinGuo** [Panman8201/ember-cli-bootswatch#13]
Hi,
We have some issue where after upgraded to ember-cli 2.4.2, none of the bootstrap CSS / js are included in the application. Can you give me some ideas on how to determine if it is ember-cli-bootswatch at fault here. 

Out application works perfectly fine under ember-cli 2.3.0

Thanks

**Comment by Panman8201** [comment]
Just updated an app to ember-cli 2.4.2 and it seems to be working. 

1. Do you get any errors in the console when you run `ember serve` or `ember build`? 
2. And are you looking in the `vendor.js` / `vendor.css` files for the Bootswatch stuff? 
3. Finally, have you followed the "Project Update" steps in the [ember-cli release notes](https://github.com/ember-cli/ember-cli/releases/tag/v2.4.2)?
  * If so, might be worth while to try a [nombom](https://www.npmjs.com/package/nombom)

**Comment by ShenglinGuo** [comment]
I think you are correct, probably have nothing to do with ember-cli-bootwatch, I just realise the problem is vendor.css is completely empty. 

There is no error in the console when doing ember build, we are using ember-cli-sass so I guess  that is the next thing to check. 

Thank you for you help

**Comment by ShenglinGuo** [comment]
Just for your information, the culprit of our problem is actually ember-component-css addon
https://github.com/ebryn/ember-component-css/issues/122
