### ISSUE TITLE
Start using npm instead of Bower for this add-on?

### ISSUE THREAD

**Issue by acorncom** [Panman8201/ember-cli-bootswatch#14]
With the ongoing shift away from Bower for Ember-CLI, would you consider switching to using npm packages instead of Bower here too?

**Comment by Panman8201** [comment]
Sure, certainly possible. Interested in writing a PR?

**Comment by Panman8201** [comment]
Learning on how to do this for another addon. But I have a question here, should the dependency be in the project/app or the addon? If it's in the addon, then the user has no way of adjusting what version of bootswatch is used...
